import axios from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import {pressCodes} from '../../../server/pressCode';
import TinyBarChart from '../../../src/components/TinyBarChart';
import {dataa} from '../../../src/data';
export default function PressDetail({data}) {
  return (
    <div className='p-2'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className=' bg-primary-dark-green h-20 flex justify-start items-center rounded-sm drop-shadow-xl p-2 sticky top-2 bg-opacity-80 z-10'>
        <nav className='flex justify-start items-center gap-12'>
          <div>
            <Image src="/images/logo.webp" alt="sisako logo" width={60} height={60}/>
          </div>
          <div className='flex-1 flex justify-start items-center gap-9'>
            <Link legacyBehavior href="/press"><a className='py-3 px-3 rounded-md hover:bg-primary-light-green transition-all duration-300'>پرس ها</a></Link>
            <Link legacyBehavior href="/die"><a className='py-3 px-3 rounded-md hover:bg-primary-light-green transition-all duration-300'>قالب ها</a></Link>
            <Link legacyBehavior href="/personnel"><a className='py-3 px-3 rounded-md hover:bg-primary-light-green transition-all duration-300'> پرسنل</a></Link>
          </div>
        </nav>
      </header>
      <main className='grid grid-cols-1 md:grid-cols-2  gap-10 py-4  mt-10 mb-20 container mx-auto'>
        
        {/* press card */}
        <div className='grid grid-cols-2 bg-primary-light-green drop-shadow-2xl shadow-primary-dark-green shadow-md p-2 rounded-md gap-4'>
          <div className='aspect-w-1 aspect-h-1 '>
            <img src={`/images/press/press/${data.id}.jpg`} alt="press" className='w-full h-full object-center object-cover rounded-sm' />
          </div>
          <div className='flex flex-col gap-10 justify-center items-start'>
            <div className='flex items-center gap-2'>
              <h2>کد پرس :</h2>
              <p className='font-bold'>{data.id}</p>
            </div>
            <div className='flex items-center gap-2'>
              <h2>مشخصات پرس :</h2>
              <p className='font-bold'>{data.name}</p>
            </div>
            <div className='flex items-center gap-2'>
              <h2>کشور سازنده:</h2>
              <p className='font-bold'>{data.maker}</p>
            </div>
          </div>
        </div>
        {/* one chart */}
        <div className='p-2 bg-primary-light-green rounded-md'>
          <TinyBarChart data={dataa} title="OEE"/>
        </div>
      </main>
      
    <footer className='fixed bottom-0 right-0 left-2 bg-primary-dark-green h-20 w-full flex justify-center items-center'>
        <p>با بیش از بیست سال سابقه کار در صنعت خودرو</p>
      </footer>
    </div>
  )
};
export async function getStaticPaths() {
    const paths=pressCodes.map(item=>{
        return {params:{slug:item}}; 
    })
  return {
    paths:paths,
    fallback: false,
  }
};
export async function getStaticProps({params}) {
  console.log(params)
const {data}= await axios.get(`http://localhost:4000/press/${params.slug}`);
console.log(data)
  return {
    props: {
      data
    }, 
  }
}
