import axios from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import {pressCodes} from '../../../server/pressCode';


export default function PressDetail({data}) {
  console.log(data)
  return (
    <div className='p-2'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className='bg-sky-500 h-20 flex justify-start items-center rounded-sm drop-shadow-xl p-2 sticky top-2 bg-opacity-80 z-10'>
        <nav className='flex justify-start items-center gap-12'>
          <div>
            <Link href={'/'} legacyBehavior><a className='bg-red-500 w-full'><Image src="/images/logo.webp" alt="sisako logo" width={60} height={60}/></a></Link>
          </div>
          <div className='flex-1 flex justify-start items-center gap-9'>
            <Link legacyBehavior href="/press"><a className='py-3 px-3 rounded-md hover:bg-sky-600 transition-all duration-300'>پرس ها</a></Link>
            <Link legacyBehavior href="#"><a className='py-3 px-3 rounded-md hover:bg-sky-600 transition-all duration-300'>قالب ها</a></Link>
            <Link legacyBehavior href="#"><a className='py-3 px-3 rounded-md hover:bg-sky-600 transition-all duration-300'> پرسنل</a></Link>
          </div>
        </nav>
      </header>
    <main className='flex flex-col justify-center items-center gap-10 py-4'>
        <div className='flex justify-start items-center gap-4  bg-slate-700 bg-opacity-30 shadow-lg drop-shadow-lg rounded-md w-full p-2'>
        <div className='rounded-md overflow-hidden'>
          <img src={`/images/press/press/${data.id}.jpg`} alt="press" class="w-48 h-48 object-center object-cover" />
        </div>
          <div className='flex-1 flex flex-col gap-10 justify-start items-start text-sky-400 text-lg '>
          <div className='flex items-center gap-2'>
            <h2>کد پرس :</h2>
            <p>{data.id}</p>
          </div>
          <div className='flex items-center gap-2'>
            <h2>مشخصات پرس :</h2>
            <p>{data.name}</p>
          </div>
          <div className='flex items-center gap-2'>
            <h2>کشور سازنده:</h2>
            <p>{data.maker}</p>
          </div>
          </div>
        </div>
    </main>
      
      <footer className='fixed bottom-0 right-0 left-2 bg-sky-500 h-20 w-full flex justify-center items-center'>
        <p>با بیش از بیست سال سابقه کار در صنعت خودرو</p>
      </footer>
    </div>
  )
};
export async function getStaticPaths() {
    const paths=pressCodes.map(item=>{
        return {params:{slug:item}}; 
    })
  return {
    paths:paths,
    fallback: false,
  }
};
export async function getStaticProps({params}) {
  console.log(params)
const {data}= await axios.get(`http://localhost:4000/press/${params.slug}`);
console.log(data)
  return {
    props: {
      data
    }, 
  }
}
