import axios from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useEffect, useState } from 'react';


export default function Type({kind}) {
  const [presses,setPresses]=useState({data:null,error:null,loading:false});
  console.log(kind);
  useEffect(()=>{
    setPresses({data:null,error:null,loading:true})
    axios.get(`http://localhost:4000/press?type=${kind}`)
    .then(res=>{
      setPresses({data:res.data,error:null,loading:false})
    })
    .catch(err=>{
      setPresses({data:null,error:err.message,loading:false})
    })
  },[])
  return (
    <div className='p-2'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className=' bg-primary-dark-green h-20 flex justify-start items-center rounded-sm drop-shadow-xl p-2 sticky top-2 bg-opacity-80 z-10'>
        <nav className='flex justify-start items-center gap-12'>
          <div>
            <Image src="/images/logo.webp" alt="sisako logo" width={60} height={60}/>
          </div>
          <div className='flex-1 flex justify-start items-center gap-9'>
            <Link legacyBehavior href="/press"><a className='py-3 px-3 rounded-md hover:bg-primary-light-green transition-all duration-300'>پرس ها</a></Link>
            <Link legacyBehavior href="/die"><a className='py-3 px-3 rounded-md hover:bg-primary-light-green transition-all duration-300'>قالب ها</a></Link>
            <Link legacyBehavior href="/personnel"><a className='py-3 px-3 rounded-md hover:bg-primary-light-green transition-all duration-300'> پرسنل</a></Link>
          </div>
        </nav>
      </header>
      {presses.data &&  presses.data.length >0 && 
    <main className='grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-10 py-4  mt-10 mb-20 container mx-auto'>
      {presses.data.map(item=>{
        return  <div className='bg-primary-light-green drop-shadow-2xl shadow-primary-dark-green shadow-md p-2 rounded-md'>
          <Link key={item.id} href={`/press/detail/${item.id}`} legacyBehavior><a className='w-full'>
          <div className='grid grid-cols-2  gap-4'>
            <div className='aspect-w-1 aspect-h-1 '>
              <img src={item.image} alt="press" className='w-full h-full object-center object-cover rounded-sm' />
            </div>
            <div className='flex flex-col gap-16 justify-center items-start'>
              <div className='flex items-center gap-2'>
                <h2>کد پرس :</h2>
                <p className='font-bold'>{item.id}</p>
              </div>
              <div className='flex items-center gap-2'>
                <h2>مشخصات پرس :</h2>
                <p className='font-bold'>{item.name}</p>
              </div>
            </div>
          </div>
          </a></Link>
        </div>
          
      })}

    </main>
    }
      
      <footer className='fixed bottom-0 right-0 left-2 bg-primary-dark-green h-20 w-full flex justify-center items-center'>
        <p>با بیش از بیست سال سابقه کار در صنعت خودرو</p>
      </footer>
    </div>
  )
};
export async function getStaticPaths() {
  return {
    paths: [
      { params: { type: 'ضربه ای' } },
      { params: { type: 'هیدرولیک' } },
      { params: { type: 'پرس جوش' } },
      { params: { type: 'جوش co2' } },
      { params: { type: 'گان' } },
    ],
    fallback: false,
  }
};
export async function getStaticProps({params}) {
  const kind=params;
  console.log(params.type)
const {data}= await axios.get(`http://localhost:4000/press?type=${params.type}`);
  return {
    props: {
      kind:kind.type
    },
  }
}
